### ISSUE TITLE
tox will break with the release of tox4

### ISSUE THREAD

**Issue by jugmac00** [plone/Products.ExtendedPathIndex#18]
Hi

while tox currently passes, the upcoming tox4 (currently available as alpha) will break.

I noticed that when I ran tox for all Zope and Plone repos this weekend ( https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/ ).

```
❯ tox4 -r -e py38
py38: remove tox env folder /home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38
py38: install_deps> python -I -m pip install setuptools zc.buildout
py38: commands[0]> .tox/4/py38/bin/buildout -c /home/jugmac00/Projects/Products.ExtendedPathIndex/buildout.cfg buildout:directory=/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38 buildout:develop=/home/jugmac00/Projects/Products.ExtendedPathIndex bootstrap
Creating directory '/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/eggs'.
Creating directory '/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/parts'.
Creating directory '/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/develop-eggs'.
Generated script '/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/bin/buildout'.
py38: commands[1]> .tox/4/py38/bin/buildout -c /home/jugmac00/Projects/Products.ExtendedPathIndex/buildout.cfg buildout:directory=/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38 buildout:develop=/home/jugmac00/Projects/Products.ExtendedPathIndex
Develop: '/home/jugmac00/Projects/Products.ExtendedPathIndex'
warning: no previously-included files found matching '.installed.cfg'
warning: no previously-included files matching '*' found under directory 'news'
warning: no previously-included files found matching 'news'
Getting distribution for 'zc.recipe.testrunner==2.2'.
Got zc.recipe.testrunner 2.2.
Getting distribution for 'zope.testrunner==5.2'.
Got zope.testrunner 5.2.
Getting distribution for 'zc.recipe.egg==2.0.7'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'main' from 'setuptools.command.easy_install' (/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/setuptools/command/easy_install.py)
An error occurred when trying to install /tmp/tmpks8y6lvuget_dist/zc.recipe.egg-2.0.7.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing.
  Getting section test.
  Initializing section test.
  Installing recipe zc.recipe.testrunner.
  Getting distribution for 'zc.recipe.egg==2.0.7'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 701, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 701, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1324, in __getitem__
    options._initialize()
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1432, in _initialize
    self.initialize()
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1438, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1381, in _install_and_load
    zc.buildout.easy_install.install(
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)
py38: exit 1 (2.21 seconds) /home/jugmac00/Projects/Products.ExtendedPathIndex> .tox/4/py38/bin/buildout -c /home/jugmac00/Projects/Products.ExtendedPathIndex/buildout.cfg buildout:directory=/home/jugmac00/Projects/Products.ExtendedPathIndex/.tox/4/py38 buildout:develop=/home/jugmac00/Projects/Products.ExtendedPathIndex pid=14680
  py38: FAIL code 1 (4.27=setup[1.36]+cmd[0.71,2.21] seconds)
  evaluation failed :( (4.30 seconds)
```

I had success to fix the build when I pinned setuptools to 51.3.3 - with 52 easy_install was removed.

As I have no experience with this package, I leave somebody else the chance to fix the build.

**Comment by jugmac00** [comment]
see https://github.com/buildout/buildout/pull/549
